import type { LandingIconName } from '@/lib/constants/landing';
import type { ServiceKey } from './theme';

export type Solution = {
  id: string;
  serviceKey: ServiceKey;
  badge: string;
  title: string;
  description: string;
  metrics: Array<{ value: string; label: string }>;
  challenge: string;
  modules: string[];
  outcome: string;
  icon: LandingIconName;
  image?: string;
  href: string;
};

export const solutions: Solution[] = [
  {
    id: 'crm-client-management',
    serviceKey: 'it',
    badge: 'Client growth',
    title: 'Client Relationship Management Platform',
    description: 'A CRM platform for lead tracking, follow-up reminders, client profiles, pipeline visibility, and management reporting.',
    metrics: [{ value: 'Faster', label: 'Follow-up rhythm' }, { value: 'Clear', label: 'Lead tracking' }],
    challenge: 'Sales teams lose momentum when client notes, reminders, and pipeline ownership stay scattered.',
    modules: ['Lead pipeline', 'Client profiles', 'Follow-up reminders', 'Management dashboard'],
    outcome: 'Cleaner sales rhythm and stronger client accountability.',
    icon: 'Bot',
    image: '/solutions/nexus-crm.webp',
    href: '/contact',
  },
  {
    id: 'business-process-automation',
    serviceKey: 'consultancy',
    badge: 'Operating control',
    title: 'Business Process Automation System',
    description: 'A structured workflow layer for approvals, tasks, reminders, reporting, and role ownership.',
    metrics: [{ value: 'Faster', label: 'Request routing' }, { value: 'Always on', label: 'Process visibility' }],
    challenge: 'Repeated approvals, handoffs, and status updates consume management time without improving control.',
    modules: ['SOP mapping', 'Approval flow', 'Task engine', 'KPI reporting'],
    outcome: 'Less dependency on manual coordination.',
    icon: 'Workflow',
    href: '/contact',
  },
  {
    id: 'tax-vat-compliance',
    serviceKey: 'consultancy',
    badge: 'Compliance',
    title: 'Tax, VAT & Compliance Management System',
    description: 'A control layer for deadlines, filings, evidence, obligations, and advisory review notes.',
    metrics: [{ value: 'Clear', label: 'Deadline tracking' }, { value: '1 place', label: 'Evidence control' }],
    challenge: 'Compliance work becomes risky when documents, due dates, and review notes live in separate places.',
    modules: ['Tax calendar', 'VAT tracker', 'Document vault', 'Compliance review'],
    outcome: 'Better preparedness for statutory and management decisions.',
    icon: 'FileCheck2',
    href: '/contact',
  },
  {
    id: 'legal-document-platform',
    serviceKey: 'legal',
    badge: 'Risk readiness',
    title: 'Legal Case / Document Management Platform',
    description: 'A secure system for documents, cases, deadlines, policies, compliance checks, and risk tracking.',
    metrics: [{ value: 'Organized', label: 'Document readiness' }, { value: '1 view', label: 'Risk tracking' }],
    challenge: 'Legal and compliance files become hard to trust when versions, deadlines, and owners are unclear.',
    modules: ['Case tracker', 'Document vault', 'Policy library', 'Risk register'],
    outcome: 'Better visibility across legal obligations.',
    icon: 'Scale',
    href: '/contact',
  },
  {
    id: 'management-dashboard-kpi',
    serviceKey: 'consultancy',
    badge: 'Leadership visibility',
    title: 'Management Dashboard & KPI Reporting System',
    description: 'A leadership command view for performance metrics, reviews, decisions, and business priorities.',
    metrics: [{ value: 'Current', label: 'Decision visibility' }, { value: 'Assigned', label: 'KPI ownership' }],
    challenge: 'Leadership decisions slow down when reports arrive late and performance ownership is not visible.',
    modules: ['KPI map', 'Review cadence', 'Performance alerts', 'Decision log'],
    outcome: 'Faster leadership decisions with less ambiguity.',
    icon: 'LineChart',
    href: '/contact',
  },
  {
    id: 'accounting-financial-control',
    serviceKey: 'consultancy',
    badge: 'Finance control',
    title: 'Accounting & Financial Control System',
    description: 'A structured finance operating model for bookkeeping, reporting, cash visibility, and approvals.',
    metrics: [{ value: 'Monthly', label: 'MIS rhythm' }, { value: 'Checked', label: 'Payment control' }],
    challenge: 'Finance teams need a reliable control model before reports, approvals, and cash decisions can scale.',
    modules: ['Chart of accounts', 'Payment control', 'Cash flow view', 'Monthly MIS'],
    outcome: 'A more reliable finance backbone for operators.',
    icon: 'BarChart3',
    href: '/contact',
  },
  {
    id: 'creative-brand-website',
    serviceKey: 'creative',
    badge: 'Market presence',
    title: 'Creative Brand & Website Experience',
    description: 'A brand and website system that clarifies the offer and improves trust at first contact.',
    metrics: [{ value: 'Clear', label: 'Brand signal' }, { value: 'Simple', label: 'Conversion path' }],
    challenge: 'Strong companies lose credibility when their brand, pitch assets, and website do not match their value.',
    modules: ['Identity system', 'Website UX', 'Content direction', 'Pitch assets'],
    outcome: 'A sharper market signal and higher conversion confidence.',
    icon: 'Palette',
    href: '/contact',
  },
  {
    id: 'custom-business-os',
    serviceKey: 'it',
    badge: 'Custom operations',
    title: 'Custom Internal Business Operating System',
    description: 'A role-based operating platform for internal tools, reporting, data, tasks, workflows, and team operations.',
    metrics: [{ value: '1 system', label: 'Operational source' }, { value: 'Role-based', label: 'Access control' }],
    challenge: 'Growing teams need one operating layer instead of disconnected spreadsheets, chats, and manual reports.',
    modules: ['Role access', 'Data model', 'Workflow tools', 'Admin console'],
    outcome: 'A central system built around how the company really works.',
    icon: 'Network',
    image: '/solutions/custom-internal-business-os.webp',
    href: '/contact',
  },
  {
    id: 'document-review-workflow',
    serviceKey: 'it',
    badge: 'Document ops',
    title: 'Document Review Workflow',
    description: 'A document review and extraction workflow for contracts, reports, policies, leases, and recurring paperwork.',
    metrics: [{ value: 'Faster', label: 'Data capture' }, { value: 'Shorter', label: 'Review cycle' }],
    challenge: 'Teams spend too much time reading repeated documents and manually copying important clauses or data.',
    modules: ['PDF extraction', 'Clause detection', 'Structured reports', 'Review workflow'],
    outcome: 'Faster document handling with a cleaner audit trail.',
    icon: 'FileCheck2',
    image: '/solutions/legal-document-intelligence.jpeg',
    href: '/contact',
  },
  {
    id: 'meal-planning-nutrition',
    serviceKey: 'it',
    badge: 'Planning tool',
    title: 'Meal Planning & Nutrition Assistant',
    description: 'A personalized meal planning system with weekly plans, nutrition scoring, smart swaps, and family profiles.',
    metrics: [{ value: 'Guided', label: 'Planning assistant' }, { value: 'Weekly', label: 'Meal schedule' }],
    challenge: 'Families need guided meal planning without manual nutrition tracking, shopping list work, and repeated decision fatigue.',
    modules: ['Meal planner', 'Nutrition score', 'Voice logging', 'Family profiles'],
    outcome: 'Healthier planning with less weekly friction.',
    icon: 'Bot',
    image: '/solutions/ai-meal-planning-nutrition.webp',
    href: '/contact',
  },
  {
    id: 'charity-community-data',
    serviceKey: 'it',
    badge: 'Impact data',
    title: 'Charity Data and Community Records Platform',
    description: 'A social-impact data platform for nonprofit records, community signals, impact dashboards, categorization, and donor reporting.',
    metrics: [{ value: 'Unified', label: 'Impact records' }, { value: 'Clear', label: 'Community insights' }],
    challenge: 'Impact teams struggle when grant data, program data, financial records, and community signals are fragmented.',
    modules: ['Data unification', 'Impact dashboard', 'Record categories', 'Community mapping'],
    outcome: 'Clearer community intelligence for better social-impact decisions.',
    icon: 'BrainCircuit',
    image: '/solutions/ai-charity-community-intelligence.webp',
    href: '/contact',
  },
  {
    id: 'audience-insights',
    serviceKey: 'it',
    badge: 'Audience data',
    title: 'Audience Insights Platform',
    description: 'A first-party customer data platform for segmentation, persona notes, engagement analysis, and campaign insights.',
    metrics: [{ value: 'Unified', label: 'Profile records' }, { value: 'Clear', label: 'Persona notes' }],
    challenge: 'Marketing teams need usable customer understanding without manually stitching CRM, CSV, SQL, and warehouse data.',
    modules: ['Data connectors', 'Audience groups', 'Persona notes', 'Engagement scoring'],
    outcome: 'Smarter targeting from unified first-party data.',
    icon: 'LineChart',
    image: '/solutions/ai-audience-intelligence.webp',
    href: '/contact',
  },
  {
    id: 'modern-data-warehouse-bi',
    serviceKey: 'it',
    badge: 'BI platform',
    title: 'Data Warehouse and BI Platform',
    description: 'A governed analytics layer with data pipelines, dashboards, plain-language reporting, and secure role-based access.',
    metrics: [{ value: '1 source', label: 'Trusted data' }, { value: 'Clear', label: 'Reporting view' }],
    challenge: 'Leadership cannot move fast when reporting lives across disconnected tools and manual spreadsheet processes.',
    modules: ['Data warehouse', 'ETL pipelines', 'BI dashboards', 'Reporting notes'],
    outcome: 'Faster decisions from governed business intelligence.',
    icon: 'DatabaseZap',
    image: '/solutions/modern-data-warehouse-bi.webp',
    href: '/contact',
  },
  {
    id: 'media-distribution-pipeline',
    serviceKey: 'it',
    badge: 'Media ops',
    title: 'Multi-Channel Media Distribution Pipeline',
    description: 'A media operations pipeline for ingestion, transcription, metadata, thumbnails, rights checks, scheduling, and channel publishing.',
    metrics: [{ value: 'Batch', label: 'Asset handling' }, { value: 'Quick', label: 'Recovery flow' }],
    challenge: 'Content teams lose time when long-form video needs manual repackaging, metadata, scheduling, and publishing across channels.',
    modules: ['Media ingestion', 'Transcription', 'Channel fit', 'Auto publishing'],
    outcome: 'A scalable content pipeline from upload to multi-channel distribution.',
    icon: 'CloudCog',
    image: '/solutions/ai-media-distribution-pipeline.webp',
    href: '/contact',
  },
  {
    id: 'employee-leave-field-monitoring',
    serviceKey: 'it',
    badge: 'Workforce',
    title: 'Employee Leave and Field Monitoring Mobile Application',
    description: 'A mobile-first workforce platform for leave requests, approvals, field check-ins, GPS visibility, and activity reporting.',
    metrics: [{ value: 'Live', label: 'Field visibility' }, { value: 'Mobile', label: 'Leave workflow' }],
    challenge: 'Field teams need fast approvals and location visibility without scattered chat updates and manual attendance tracking.',
    modules: ['Leave management', 'Smart approvals', 'GPS monitoring', 'Reports'],
    outcome: 'Cleaner workforce visibility for distributed teams.',
    icon: 'Workflow',
    image: '/solutions/employee-leave-field-monitoring.webp',
    href: '/contact',
  },
  {
    id: 'contract-policy-workbench',
    serviceKey: 'legal',
    badge: 'Documentation',
    title: 'Contract & Policy Documentation Workbench',
    description: 'A guided system for drafting, reviewing, storing, and tracking business documentation.',
    metrics: [{ value: 'Versioned', label: 'Document control' }, { value: 'Faster', label: 'Review handoff' }],
    challenge: 'Organizations need consistent documentation without losing track of approvals, versions, and responsible teams.',
    modules: ['Template library', 'Review notes', 'Version history', 'Approval status'],
    outcome: 'More reliable documentation coordination without claiming to replace legal counsel.',
    icon: 'FileCheck2',
    href: '/contact',
  },
  {
    id: 'compliance-risk-register',
    serviceKey: 'legal',
    badge: 'Governance',
    title: 'Compliance & Legal Risk Register',
    description: 'A structured register for obligations, documentation gaps, policy updates, and risk review.',
    metrics: [{ value: 'Live', label: 'Risk view' }, { value: 'Clear', label: 'Owner mapping' }],
    challenge: 'Compliance exposure grows when risks are discussed but not assigned, tracked, or reviewed regularly.',
    modules: ['Risk register', 'Obligation tracker', 'Owner matrix', 'Review cadence'],
    outcome: 'Better governance visibility for management review.',
    icon: 'Scale',
    href: '/contact',
  },
  {
    id: 'brand-launch-system',
    serviceKey: 'creative',
    badge: 'Launch system',
    title: 'Brand Launch & Market Communication System',
    description: 'A complete launch layer for positioning, campaign assets, pitch content, and digital storytelling.',
    metrics: [{ value: 'Unified', label: 'Brand language' }, { value: 'Ready', label: 'Launch assets' }],
    challenge: 'Campaigns feel weak when design, messaging, offer clarity, and sales assets are built separately.',
    modules: ['Brand story', 'Campaign assets', 'Pitch deck', 'Social content'],
    outcome: 'A more confident and consistent market launch.',
    icon: 'Palette',
    href: '/contact',
  },
  {
    id: 'conversion-landing-system',
    serviceKey: 'creative',
    badge: 'Conversion',
    title: 'Conversion Landing Page & Proposal System',
    description: 'A focused digital experience that turns offers into clear pages, proposals, and client-ready materials.',
    metrics: [{ value: 'Sharper', label: 'Offer clarity' }, { value: 'Higher', label: 'Inquiry confidence' }],
    challenge: 'Good offers fail to convert when the page, proposal, and message hierarchy do not guide the buyer.',
    modules: ['Landing page', 'Proposal deck', 'CTA flow', 'Content hierarchy'],
    outcome: 'A clearer buyer journey from first impression to inquiry.',
    icon: 'Workflow',
    href: '/contact',
  },
];

export const aiCapabilities = [
  {
    title: 'Workflow Automation',
    description: 'Approval handoffs, reminders, document flows, and status triggers for recurring office work.',
    benefit: 'Less manual coordination',
    icon: 'Workflow' as const,
  },
  {
    title: 'Support Assistants',
    description: 'Inbox triage, FAQ drafts, internal knowledge lookup, and sales notes connected to approved sources.',
    benefit: 'Faster first replies',
    icon: 'Bot' as const,
  },
  {
    title: 'Business Software',
    description: 'Custom portals, admin systems, and role-based platforms for work that has outgrown spreadsheets.',
    benefit: 'Built around real operations',
    icon: 'Code2' as const,
  },
  {
    title: 'CRM / ERP',
    description: 'Lead, client, sales, inventory, accounting, and workflow modules tied to department owners.',
    benefit: 'Connected departments',
    icon: 'Network' as const,
  },
  {
    title: 'Dashboards',
    description: 'KPI dashboards, management packs, performance alerts, and executive views with named owners.',
    benefit: 'Clearer decisions',
    icon: 'LineChart' as const,
  },
  {
    title: 'Document Automation',
    description: 'Template systems, approval flows, guided drafting, document repositories, and version checks.',
    benefit: 'More reliable documentation',
    icon: 'FileCheck2' as const,
  },
  {
    title: 'Company Knowledge Search',
    description: 'Search over company files, policies, SOPs, cases, and internal notes with access-aware answers.',
    benefit: 'Reusable knowledge',
    icon: 'BrainCircuit' as const,
  },
  {
    title: 'API Integrations',
    description: 'Connect websites, CRMs, spreadsheets, dashboards, payment systems, and internal tools without duplicate entry.',
    benefit: 'Less disconnected data',
    icon: 'CloudCog' as const,
  },
];

export const caAdvisoryFocus = [
  'Taxation Advisory',
  'VAT Advisory',
  'Customs & Bond Advisory',
  'Business Health Checkup',
  'Accounting System Setup',
  'Financial Reporting',
  'Internal Control',
  'SOP Development',
  'Budgeting & Forecasting',
  'Cash Flow Management',
  'KPI Dashboard',
  'Due Diligence',
  'Feasibility Study',
  'Business Plan',
  'Financial Modeling',
  'Audit Support',
  'Corporate Governance',
];
