import type { LandingIconName } from '@/lib/constants/landing';
import type { ServiceKey } from './theme';

export type Solution = {
  id: string;
  serviceKey: ServiceKey;
  badge: string;
  title: string;
  description: string;
  metrics: Array<{ value: string; label: string }>;
  challenge: string;
  modules: string[];
  outcome: string;
  icon: LandingIconName;
  href: string;
};

export const solutions: Solution[] = [
  {
    id: 'ai-crm-client-management',
    serviceKey: 'it',
    badge: 'Client growth',
    title: 'AI-powered CRM & Client Management System',
    description: 'A lead, client, follow-up, document, and reporting system strengthened by AI-assisted actions.',
    metrics: [{ value: '38%', label: 'Faster follow-up' }, { value: '0 lag', label: 'Lead tracking' }],
    challenge: 'Sales teams lose momentum when client notes, reminders, and pipeline ownership stay scattered.',
    modules: ['Lead pipeline', 'Client profiles', 'AI follow-ups', 'Executive dashboard'],
    outcome: 'Cleaner sales rhythm and stronger client accountability.',
    icon: 'Bot',
    href: '/contact',
  },
  {
    id: 'business-process-automation',
    serviceKey: 'consultancy',
    badge: 'Operating control',
    title: 'Business Process Automation System',
    description: 'A structured workflow layer for approvals, tasks, reminders, reporting, and role ownership.',
    metrics: [{ value: '10x', label: 'Faster routing' }, { value: '24/7', label: 'Process visibility' }],
    challenge: 'Repeated approvals, handoffs, and status updates consume management time without improving control.',
    modules: ['SOP mapping', 'Approval flow', 'Task engine', 'KPI reporting'],
    outcome: 'Less dependency on manual coordination.',
    icon: 'Workflow',
    href: '/contact',
  },
  {
    id: 'tax-vat-compliance',
    serviceKey: 'consultancy',
    badge: 'Compliance',
    title: 'Tax, VAT & Compliance Management System',
    description: 'A control layer for deadlines, filings, evidence, obligations, and advisory review notes.',
    metrics: [{ value: '100%', label: 'Deadline tracking' }, { value: '1 vault', label: 'Evidence control' }],
    challenge: 'Compliance work becomes risky when documents, due dates, and review notes live in separate places.',
    modules: ['Tax calendar', 'VAT tracker', 'Document vault', 'Compliance review'],
    outcome: 'Better preparedness for statutory and management decisions.',
    icon: 'FileCheck2',
    href: '/contact',
  },
  {
    id: 'legal-document-platform',
    serviceKey: 'legal',
    badge: 'Risk readiness',
    title: 'Legal Case / Document Management Platform',
    description: 'A secure system for documents, cases, deadlines, policies, compliance checks, and risk tracking.',
    metrics: [{ value: '95%+', label: 'Document readiness' }, { value: '1 view', label: 'Risk tracking' }],
    challenge: 'Legal and compliance files become hard to trust when versions, deadlines, and owners are unclear.',
    modules: ['Case tracker', 'Document vault', 'Policy library', 'Risk register'],
    outcome: 'Better visibility across legal obligations.',
    icon: 'Scale',
    href: '/contact',
  },
  {
    id: 'management-dashboard-kpi',
    serviceKey: 'consultancy',
    badge: 'Leadership visibility',
    title: 'Management Dashboard & KPI Reporting System',
    description: 'A leadership command view for performance metrics, reviews, decisions, and business priorities.',
    metrics: [{ value: 'Real-time', label: 'Decision visibility' }, { value: '100%', label: 'KPI ownership' }],
    challenge: 'Leadership decisions slow down when reports arrive late and performance ownership is not visible.',
    modules: ['KPI map', 'Review cadence', 'Performance alerts', 'Decision log'],
    outcome: 'Faster leadership decisions with less ambiguity.',
    icon: 'LineChart',
    href: '/contact',
  },
  {
    id: 'accounting-financial-control',
    serviceKey: 'consultancy',
    badge: 'Finance control',
    title: 'Accounting & Financial Control System',
    description: 'A structured finance operating model for bookkeeping, reporting, cash visibility, and approvals.',
    metrics: [{ value: 'Monthly', label: 'MIS rhythm' }, { value: '100%', label: 'Payment control' }],
    challenge: 'Finance teams need a reliable control model before reports, approvals, and cash decisions can scale.',
    modules: ['Chart of accounts', 'Payment control', 'Cash flow view', 'Monthly MIS'],
    outcome: 'A more reliable finance backbone for operators.',
    icon: 'BarChart3',
    href: '/contact',
  },
  {
    id: 'creative-brand-website',
    serviceKey: 'creative',
    badge: 'Market presence',
    title: 'Creative Brand & Website Experience',
    description: 'A premium brand and website system that clarifies the offer and improves trust at first contact.',
    metrics: [{ value: 'Premium', label: 'Brand signal' }, { value: 'Clear', label: 'Conversion path' }],
    challenge: 'Strong companies lose credibility when their brand, pitch assets, and website do not match their value.',
    modules: ['Identity system', 'Website UX', 'Content direction', 'Pitch assets'],
    outcome: 'A sharper market signal and higher conversion confidence.',
    icon: 'Palette',
    href: '/contact',
  },
  {
    id: 'custom-business-os',
    serviceKey: 'it',
    badge: 'Custom operations',
    title: 'Custom Internal Business Operating System',
    description: 'A role-based operating platform for internal tools, reporting, data, tasks, and team workflows.',
    metrics: [{ value: '1 system', label: 'Operational source' }, { value: 'Role-based', label: 'Access control' }],
    challenge: 'Growing teams need one operating layer instead of disconnected spreadsheets, chats, and manual reports.',
    modules: ['Role access', 'Data model', 'Workflow tools', 'Admin console'],
    outcome: 'A central system built around how the company really works.',
    icon: 'Network',
    href: '/contact',
  },
  {
    id: 'ai-document-intelligence',
    serviceKey: 'it',
    badge: 'AI document ops',
    title: 'AI Document Intelligence Platform',
    description: 'A document review and extraction system for contracts, reports, policies, and recurring paperwork.',
    metrics: [{ value: '90%+', label: 'Extraction accuracy' }, { value: 'Minutes', label: 'Review cycle' }],
    challenge: 'Teams spend too much time reading repeated documents and manually copying important clauses or data.',
    modules: ['PDF extraction', 'Clause detection', 'Structured reports', 'Review workflow'],
    outcome: 'Faster document handling with a cleaner audit trail.',
    icon: 'BrainCircuit',
    href: '/contact',
  },
  {
    id: 'contract-policy-workbench',
    serviceKey: 'legal',
    badge: 'Documentation',
    title: 'Contract & Policy Documentation Workbench',
    description: 'A guided system for drafting, reviewing, storing, and tracking business documentation.',
    metrics: [{ value: 'Versioned', label: 'Document control' }, { value: 'Faster', label: 'Review handoff' }],
    challenge: 'Organizations need consistent documentation without losing track of approvals, versions, and responsible teams.',
    modules: ['Template library', 'Review notes', 'Version history', 'Approval status'],
    outcome: 'More reliable documentation coordination without claiming to replace legal counsel.',
    icon: 'FileCheck2',
    href: '/contact',
  },
  {
    id: 'compliance-risk-register',
    serviceKey: 'legal',
    badge: 'Governance',
    title: 'Compliance & Legal Risk Register',
    description: 'A structured register for obligations, documentation gaps, policy updates, and risk review.',
    metrics: [{ value: 'Live', label: 'Risk view' }, { value: 'Clear', label: 'Owner mapping' }],
    challenge: 'Compliance exposure grows when risks are discussed but not assigned, tracked, or reviewed regularly.',
    modules: ['Risk register', 'Obligation tracker', 'Owner matrix', 'Review cadence'],
    outcome: 'Better governance visibility for management review.',
    icon: 'Scale',
    href: '/contact',
  },
  {
    id: 'brand-launch-system',
    serviceKey: 'creative',
    badge: 'Launch system',
    title: 'Brand Launch & Market Communication System',
    description: 'A complete launch layer for positioning, campaign assets, pitch content, and digital storytelling.',
    metrics: [{ value: 'Unified', label: 'Brand language' }, { value: 'Ready', label: 'Launch assets' }],
    challenge: 'Campaigns feel weak when design, messaging, offer clarity, and sales assets are built separately.',
    modules: ['Brand story', 'Campaign assets', 'Pitch deck', 'Social content'],
    outcome: 'A more confident and consistent market launch.',
    icon: 'Palette',
    href: '/contact',
  },
  {
    id: 'conversion-landing-system',
    serviceKey: 'creative',
    badge: 'Conversion',
    title: 'Conversion Landing Page & Proposal System',
    description: 'A focused digital experience that turns offers into clear pages, proposals, and client-ready materials.',
    metrics: [{ value: 'Sharper', label: 'Offer clarity' }, { value: 'Higher', label: 'Inquiry confidence' }],
    challenge: 'Good offers fail to convert when the page, proposal, and message hierarchy do not guide the buyer.',
    modules: ['Landing page', 'Proposal deck', 'CTA flow', 'Content hierarchy'],
    outcome: 'A clearer buyer journey from first impression to inquiry.',
    icon: 'Workflow',
    href: '/contact',
  },
];

export const aiCapabilities = [
  {
    title: 'AI Workflow Automation',
    description: 'Automated handoffs, reminders, document flows, and operational triggers for recurring work.',
    benefit: 'Less manual coordination',
    icon: 'Workflow' as const,
  },
  {
    title: 'AI Chatbots & Assistants',
    description: 'Client support, internal knowledge, sales assistance, and FAQ assistants trained around business context.',
    benefit: 'Faster response cycles',
    icon: 'Bot' as const,
  },
  {
    title: 'Business Software',
    description: 'Custom portals, admin systems, internal tools, and role-based operating platforms.',
    benefit: 'Built around real operations',
    icon: 'Code2' as const,
  },
  {
    title: 'CRM / ERP',
    description: 'Structured lead, client, sales, inventory, accounting, and workflow modules for operational control.',
    benefit: 'Connected departments',
    icon: 'Network' as const,
  },
  {
    title: 'Dashboards',
    description: 'KPI dashboards, management reports, performance alerts, and executive visibility layers.',
    benefit: 'Clearer decisions',
    icon: 'LineChart' as const,
  },
  {
    title: 'Document Automation',
    description: 'Template systems, approval flows, AI-assisted drafting, and document repositories.',
    benefit: 'More reliable documentation',
    icon: 'FileCheck2' as const,
  },
  {
    title: 'RAG Knowledge Assistant',
    description: 'Search and answer systems over company files, policies, SOPs, cases, and internal knowledge.',
    benefit: 'Reusable intelligence',
    icon: 'BrainCircuit' as const,
  },
  {
    title: 'API Integrations',
    description: 'Connect websites, CRMs, spreadsheets, dashboards, payment systems, and internal tools.',
    benefit: 'Less disconnected data',
    icon: 'CloudCog' as const,
  },
];

export const caAdvisoryFocus = [
  'Taxation Advisory',
  'VAT Advisory',
  'Customs & Bond Advisory',
  'Business Health Checkup',
  'Accounting System Setup',
  'Financial Reporting',
  'Internal Control',
  'SOP Development',
  'Budgeting & Forecasting',
  'Cash Flow Management',
  'KPI Dashboard',
  'Due Diligence',
  'Feasibility Study',
  'Business Plan',
  'Financial Modeling',
  'Audit Support',
  'Corporate Governance',
];
