import type { ServiceKey } from './theme';

export type SubService = {
  title: string;
  summary?: string;
};

export const subServices: Record<ServiceKey, SubService[]> = {
  it: [
    { title: 'AI Workflow Automation', summary: 'Automate repetitive business work with measurable control.' },
    { title: 'AI Chatbots & Assistants' },
    { title: 'Custom Web Application Development' },
    { title: 'Business Software Development' },
    { title: 'CRM / ERP / Internal Tool Development' },
    { title: 'Dashboard & Data Analytics' },
    { title: 'Data Visualization & Business Intelligence' },
    { title: 'Website & Landing Page Development' },
    { title: 'E-commerce System Development' },
    { title: 'API Integration' },
    { title: 'Cloud & DevOps Setup' },
    { title: 'Cybersecurity Basic Review' },
    { title: 'Digital Transformation Roadmap' },
    { title: 'AI Tool Integration for Business' },
    { title: 'Document Automation' },
    { title: 'Google Workspace / Microsoft 365 Automation' },
    { title: 'No-code / Low-code Automation' },
    { title: 'RAG-based Knowledge Assistant' },
    { title: 'Customer Support Automation' },
    { title: 'Sales Funnel Automation' },
  ],
  consultancy: [
    { title: 'Taxation Advisory', summary: 'Practical tax planning and compliance support for growth-stage companies.' },
    { title: 'Corporate Tax Planning' },
    { title: 'Individual Tax Planning' },
    { title: 'VAT Advisory' },
    { title: 'Customs & Bond Advisory' },
    { title: 'Import / Export Compliance Support' },
    { title: 'Business Health Checkup' },
    { title: 'Financial Health Checkup' },
    { title: 'Accounting System Setup' },
    { title: 'Bookkeeping System Design' },
    { title: 'Management Accounts Preparation' },
    { title: 'Financial Reporting Support' },
    { title: 'IFRS / IAS Reporting Guidance' },
    { title: 'Internal Control System Design' },
    { title: 'SOP Development' },
    { title: 'Business Process Improvement' },
    { title: 'Budgeting & Forecasting' },
    { title: 'Cash Flow Management' },
    { title: 'Costing & Pricing Strategy' },
    { title: 'KPI Design & Performance Dashboard' },
    { title: 'Feasibility Study' },
    { title: 'Business Plan Preparation' },
    { title: 'Financial Modeling' },
    { title: 'Due Diligence Support' },
    { title: 'Internal Audit Support' },
    { title: 'External Audit Coordination' },
    { title: 'Risk Management Advisory' },
    { title: 'Payroll & HR Compliance Support' },
    { title: 'Vendor / Supplier Payment Control System' },
    { title: 'Inventory Control Advisory' },
    { title: 'Project Financial Management' },
    { title: 'ERP / Accounting Software Implementation Advisory' },
    { title: 'Startup Financial Structuring' },
    { title: 'SME Growth Advisory' },
    { title: 'Corporate Governance Advisory' },
    { title: 'Business Restructuring Advisory' },
    { title: 'Investment Readiness Support' },
    { title: 'Bank Loan Documentation Support' },
    { title: 'Management Reporting Framework' },
  ],
  legal: [
    { title: 'Criminal Law', summary: 'Careful document preparation and coordination support for criminal-law related matters.' },
    { title: 'Civil Law' },
    { title: 'Family Law' },
    { title: 'Property Law' },
    { title: 'Company Formation Support', summary: 'Documentation and coordination support for compliant company setup.' },
    { title: 'RJSC Documentation Support' },
    { title: 'Trade License / Business License Support' },
    { title: 'Contract Drafting Support' },
    { title: 'Agreement Review Support' },
    { title: 'Employment Documentation' },
    { title: 'HR Policy Documentation' },
    { title: 'Legal Notice Drafting Support' },
    { title: 'Compliance Documentation' },
    { title: 'Regulatory Filing Support' },
    { title: 'Board Resolution / Minutes Support' },
    { title: 'Shareholder Documentation Support' },
    { title: 'Partnership Documentation Support' },
    { title: 'Vendor Agreement Support' },
    { title: 'NDA / Confidentiality Agreement Support' },
    { title: 'Terms & Conditions / Privacy Policy Support' },
    { title: 'Business Policy Drafting' },
    { title: 'Legal Risk Review' },
    { title: 'Tax & Legal Documentation Coordination' },
    { title: 'Intellectual Property / Trademark Coordination' },
    { title: 'Dispute Documentation Support' },
    { title: 'Legal Workflow Automation' },
    { title: 'Document Management System for Legal Files' },
  ],
  creative: [
    { title: 'Architectural Design', summary: 'Conceptual planning and presentation support for built-environment projects.' },
    { title: 'Interior Design' },
    { title: 'Exterior Design' },
    { title: 'Space Planning' },
    { title: 'Brand Strategy', summary: 'Sharper positioning, message architecture, and premium market presentation.' },
    { title: 'Logo & Visual Identity Design' },
    { title: 'Corporate Profile Design' },
    { title: 'Pitch Deck Design' },
    { title: 'Business Presentation Design' },
    { title: 'Website UI/UX Design' },
    { title: 'Landing Page Design' },
    { title: 'Social Media Creative Design' },
    { title: 'Content Strategy' },
    { title: 'Copywriting' },
    { title: 'Marketing Campaign Concept' },
    { title: 'Digital Marketing Support' },
    { title: 'Video Script & Storyboard' },
    { title: 'Motion Graphics Direction' },
    { title: 'Personal Branding' },
    { title: 'Founder Branding' },
    { title: 'LinkedIn Profile / Company Page Optimization' },
    { title: 'Proposal Design' },
    { title: 'Brochure / Flyer / Marketing Material Design' },
    { title: 'Course / Training Material Design' },
    { title: 'Event / Campaign Creative Support' },
    { title: 'Creative Consultation' },
    { title: 'Brand Experience Design' },
  ],
};
