import {
  BadgeCheck,
  Sprout,
  Calculator,
  CirclePercent,
  Container,
  UserRound,
  BookOpenCheck,
  Wallet,
  Coins,
  PackageSearch,
  Gavel,
  HeartHandshake,
  House,
  Ruler,
  Armchair,
  Monitor,
  ListChecks,
  GitBranch,
  BarChart3,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarRange,
  ChartNoAxesCombined,
  CheckCircle2,
  Clapperboard,
  ClipboardCheck,
  CloudCog,
  Code2,
  Database,
  DatabaseZap,
  Factory,
  FileCheck2,
  FileSearch,
  FolderKanban,
  GraduationCap,
  HandHeart,
  Handshake,
  HardHat,
  HeartPulse,
  Landmark,
  Layers3,
  LayoutDashboard,
  Lightbulb,
  LockKeyhole,
  Mail,
  MapPinned,
  Megaphone,
  MessageSquareText,
  Network,
  Palette,
  PanelsTopLeft,
  PenTool,
  PlugZap,
  Presentation,
  ReceiptText,
  Rocket,
  Scale,
  Search,
  ServerCog,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Target,
  UsersRound,
  Workflow,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

type IconRule = {
  terms: string[];
  icon: LucideIcon;
};

const iconRules: IconRule[] = [
  { terms: ['corporate tax'], icon: Building2 },
  { terms: ['individual tax'], icon: UserRound },
  { terms: ['taxation', 'tax planning'], icon: Calculator },
  { terms: ['vat'], icon: CirclePercent },
  { terms: ['customs', 'bond advisory', 'import', 'export'], icon: Container },
  { terms: ['bookkeeping', 'ifrs', 'ias reporting'], icon: BookOpenCheck },
  { terms: ['cash flow', 'payroll'], icon: Wallet },
  { terms: ['costing', 'pricing'], icon: Coins },
  { terms: ['inventory'], icon: PackageSearch },
  { terms: ['financial modeling', 'budgeting'], icon: ChartNoAxesCombined },
  { terms: ['financial reporting', 'management accounts'], icon: BarChart3 },
  { terms: ['accounting system'], icon: Database },
  { terms: ['internal audit'], icon: ClipboardCheck },
  { terms: ['external audit'], icon: BadgeCheck },
  { terms: ['due diligence'], icon: FileSearch },
  { terms: ['sop development'], icon: ListChecks },
  { terms: ['restructuring', 'process improvement'], icon: GitBranch },
  { terms: ['criminal law'], icon: Gavel },
  { terms: ['family law'], icon: HeartHandshake },
  { terms: ['property law'], icon: House },
  { terms: ['contract'], icon: PenTool },
  { terms: ['company formation'], icon: Building2 },
  { terms: ['architectural', 'space planning'], icon: Ruler },
  { terms: ['interior'], icon: Armchair },
  { terms: ['exterior'], icon: House },
  { terms: ['logo', 'visual identity'], icon: PenTool },
  { terms: ['ui/ux', 'interface'], icon: Monitor },
  { terms: ['pitch deck', 'corporate profile'], icon: Presentation },
  { terms: ['conference', 'seminar', 'presentation', 'speaker'], icon: Presentation },
  { terms: ['product launch', 'startup', 'mvp', 'scale up'], icon: Rocket },
  { terms: ['brand activation', 'campaign', 'marketing', 'promotion'], icon: Megaphone },
  { terms: ['workshop', 'training', 'education', 'edtech', 'learning'], icon: GraduationCap },
  { terms: ['exhibition', 'booth', 'expo'], icon: PanelsTopLeft },
  { terms: ['venue', 'vendor', 'location'], icon: MapPinned },
  { terms: ['event creative', 'media', 'video', 'content production'], icon: Clapperboard },
  { terms: ['corporate event', 'event management', 'event work'], icon: CalendarRange },
  { terms: ['real estate', 'construction', 'property'], icon: HardHat },
  { terms: ['manufacturing', 'garments', 'factory', 'production'], icon: Factory },
  { terms: ['healthcare', 'clinic', 'patient', 'health'], icon: HeartPulse },
  { terms: ['e-commerce', 'ecommerce', 'retail', 'storefront', 'shopping'], icon: ShoppingBag },
  { terms: ['ngo', 'nonprofit', 'social impact', 'donor', 'charity'], icon: HandHeart },
  { terms: ['finance', 'accounting', 'financial', 'cash flow', 'budget'], icon: Landmark },
  { terms: ['tax', 'vat', 'invoice', 'customs', 'filing'], icon: ReceiptText },
  { terms: ['legal', 'law', 'contract', 'case', 'policy'], icon: Scale },
  { terms: ['compliance', 'governance', 'audit', 'risk'], icon: ShieldCheck },
  { terms: ['security', 'secure', 'access control', 'privacy'], icon: LockKeyhole },
  { terms: ['dashboard', 'reporting', 'analytics', 'kpi', 'business intelligence'], icon: LayoutDashboard },
  { terms: ['database', 'databasezap', 'data warehouse', 'data platform', 'data model'], icon: DatabaseZap },
  { terms: ['cloud', 'cloudcog', 'devops', 'deployment', 'infrastructure'], icon: CloudCog },
  { terms: ['backend', 'server', 'servercog', 'api route'], icon: ServerCog },
  { terms: ['frontend', 'website', 'web application', 'software development', 'code2', 'code'], icon: Code2 },
  { terms: ['api integration', 'integration', 'connector'], icon: PlugZap },
  { terms: ['workflow', 'process automation', 'task routing', 'approval flow'], icon: Workflow },
  { terms: ['automation', 'trigger'], icon: Zap },
  { terms: ['crm', 'customer support', 'client relationship', 'help desk'], icon: MessageSquareText },
  { terms: ['erp', 'business operating system', 'connected department'], icon: Network },
  { terms: ['document search', 'knowledge search', 'search system', 'filesearch', 'research', 'discover'], icon: FileSearch },
  { terms: ['document', 'documentation', 'deliverable', 'handover'], icon: FileCheck2 },
  { terms: ['artificial intelligence', 'braincircuit', 'ai ', ' ai', 'machine learning', 'intelligence', 'diagnose'], icon: BrainCircuit },
  { terms: ['assistant', 'chatbot', 'bot'], icon: Bot },
  { terms: ['creative', 'brand', 'visual identity', 'ui/ux'], icon: Palette },
  { terms: ['design system', 'interface design', 'graphic design'], icon: PenTool },
  { terms: ['strategy', 'strategize', 'target', 'assessment', 'goal', 'roadmap'], icon: Target },
  { terms: ['team', 'people', 'associate', 'advisor', 'consultant'], icon: UsersRound },
  { terms: ['management', 'business advisory', 'professional service'], icon: BriefcaseBusiness },
  { terms: ['company', 'enterprise', 'sme'], icon: Building2 },
  { terms: ['portfolio', 'project', 'case study'], icon: FolderKanban },
  { terms: ['insight', 'idea', 'innovation'], icon: Lightbulb },
  { terms: ['email', 'newsletter', 'mail'], icon: Mail },
  { terms: ['search'], icon: Search },
  { terms: ['growth', 'chartnoaxescombined', 'performance', 'forecast', 'optimize'], icon: ChartNoAxesCombined },
  { terms: ['chart', 'metric'], icon: BarChart3 },
  { terms: ['partnership', 'collaboration'], icon: Handshake },
  { terms: ['quality', 'verified', 'credential'], icon: BadgeCheck },
  { terms: ['check', 'complete'], icon: CheckCircle2 },
  { terms: ['system', 'layers3', 'architecture', 'platform'], icon: Layers3 },
  { terms: ['idea', 'feature'], icon: Sparkles },
  { terms: ['shop', 'small business'], icon: Store },
  { terms: ['brief', 'checklist'], icon: ClipboardCheck },
  { terms: ['data'], icon: Database },
];

const serviceIcons: Record<string, LucideIcon> = {
  'Workflow Automation': Workflow,
  'Customer Support Assistants': Bot,
  'Custom Web Application Development': Code2,
  'Business Software Development': ServerCog,
  'CRM / ERP / Internal Tool Development': Network,
  'Dashboard & Data Analytics': LayoutDashboard,
  'Data Visualization & Business Intelligence': BarChart3,
  'Website & Landing Page Development': PanelsTopLeft,
  'E-commerce System Development': ShoppingBag,
  'API Integration': PlugZap,
  'Cloud & DevOps Setup': CloudCog,
  'Cybersecurity Basic Review': LockKeyhole,
  'Digital Systems Roadmap': MapPinned,
  'Smart Tool Integration for Business': BrainCircuit,
  'Document Automation': FileCheck2,
  'Google Workspace / Microsoft 365 Automation': CalendarRange,
  'No-code / Low-code Automation': Layers3,
  'Company Knowledge Search': FileSearch,
  'Customer Support Automation': MessageSquareText,
  'Sales Funnel Automation': Target,
  'Taxation Advisory': Calculator,
  'Corporate Tax Planning': Building2,
  'Individual Tax Planning': UserRound,
  'VAT Advisory': CirclePercent,
  'Customs & Bond Advisory': Container,
  'Import / Export Compliance Support': PackageSearch,
  'Business Health Checkup': HeartPulse,
  'Financial Health Checkup': Search,
  'Accounting System Setup': Database,
  'Bookkeeping System Design': BookOpenCheck,
  'Management Accounts Preparation': ClipboardCheck,
  'Financial Reporting Support': BarChart3,
  'IFRS / IAS Reporting Guidance': FileCheck2,
  'Internal Control System Design': LockKeyhole,
  'SOP Development': ListChecks,
  'Business Process Improvement': Workflow,
  'Budgeting & Forecasting': CalendarRange,
  'Cash Flow Management': Wallet,
  'Costing & Pricing Strategy': Coins,
  'KPI Design & Performance Dashboard': LayoutDashboard,
  'Feasibility Study': Lightbulb,
  'Business Plan Preparation': Presentation,
  'Financial Modeling': ChartNoAxesCombined,
  'Due Diligence Support': FileSearch,
  'Internal Audit Support': ShieldCheck,
  'External Audit Coordination': BadgeCheck,
  'Risk Management Advisory': Target,
  'Payroll & HR Compliance Support': UsersRound,
  'Vendor / Supplier Payment Control System': ReceiptText,
  'Inventory Control Advisory': Store,
  'Project Financial Management': FolderKanban,
  'ERP / Accounting Software Implementation Advisory': ServerCog,
  'Startup Financial Structuring': Rocket,
  'SME Growth Advisory': Sprout,
  'Corporate Governance Advisory': Scale,
  'Business Restructuring Advisory': GitBranch,
  'Investment Readiness Support': Handshake,
  'Bank Loan Documentation Support': Landmark,
  'Management Reporting Framework': PanelsTopLeft,
  'Criminal Law': Gavel,
  'Civil Law': Scale,
  'Family Law': HeartHandshake,
  'Property Law': House,
  'Company Formation Support': Building2,
  'RJSC Documentation Support': Landmark,
  'Trade License / Business License Support': BadgeCheck,
  'Contract Drafting Support': PenTool,
  'Agreement Review Support': FileSearch,
  'Employment Documentation': BriefcaseBusiness,
  'HR Policy Documentation': UsersRound,
  'Legal Notice Drafting Support': Mail,
  'Compliance Documentation': FileCheck2,
  'Regulatory Filing Support': ReceiptText,
  'Board Resolution / Minutes Support': ClipboardCheck,
  'Shareholder Documentation Support': ChartNoAxesCombined,
  'Partnership Documentation Support': Handshake,
  'Vendor Agreement Support': ShoppingBag,
  'NDA / Confidentiality Agreement Support': LockKeyhole,
  'Terms & Conditions / Privacy Policy Support': ShieldCheck,
  'Business Policy Drafting': BookOpenCheck,
  'Legal Risk Review': Search,
  'Tax & Legal Documentation Coordination': Calculator,
  'Intellectual Property / Trademark Coordination': Lightbulb,
  'Dispute Documentation Support': MessageSquareText,
  'Legal Workflow Tracking': Workflow,
  'Document Management System for Legal Files': FolderKanban,
  'Architectural Design': Ruler,
  'Interior Design': Armchair,
  'Exterior Design': House,
  'Space Planning': PanelsTopLeft,
  'Brand Strategy': Target,
  'Logo & Visual Identity Design': PenTool,
  'Corporate Profile Design': Building2,
  'Pitch Deck Design': Rocket,
  'Business Presentation Design': Presentation,
  'Website UI/UX Design': Monitor,
  'Landing Page Design': LayoutDashboard,
  'Social Media Creative Design': MessageSquareText,
  'Content Strategy': FolderKanban,
  'Copywriting': BookOpenCheck,
  'Marketing Campaign Concept': Megaphone,
  'Digital Marketing Support': ChartNoAxesCombined,
  'Video Script & Storyboard': Clapperboard,
  'Motion Graphics Direction': Zap,
  'Personal Branding': UserRound,
  'Founder Branding': BriefcaseBusiness,
  'LinkedIn Profile / Company Page Optimization': Network,
  'Proposal Design': FileCheck2,
  'Brochure / Flyer / Marketing Material Design': Layers3,
  'Course / Training Material Design': GraduationCap,
  'Event / Campaign Creative Support': CalendarRange,
  'Creative Consultation': Lightbulb,
  'Brand Experience Design': Palette,
};

const normalizedServiceIcons = new Map(Object.entries(serviceIcons).map(([title, icon]) => [title.toLowerCase(), icon]));

export function getContextIcon(context: string, fallback: LucideIcon = Sparkles): LucideIcon {
  const serviceIcon = normalizedServiceIcons.get(context.trim().toLowerCase());
  if (serviceIcon) return serviceIcon;
  const normalized = context.toLowerCase().replace(/[^a-z0-9/&+ -]/g, ' ');
  return iconRules.find((rule) => rule.terms.some((term) => normalized.includes(term)))?.icon ?? fallback;
}

type ContextIconProps = Omit<LucideProps, 'ref'> & {
  context: string;
  title?: string;
  fallback?: LucideIcon;
};

export function ContextIcon({ context, title, fallback, strokeWidth = 1.85, ...props }: ContextIconProps) {
  const Icon = title ? getContextIcon(title, getContextIcon(context, fallback)) : getContextIcon(context, fallback);
  return <Icon strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
